### ISSUE TITLE
How should I grant players permissions?

### ISSUE THREAD

**Issue by CrazyNutLz** [GTNewHorizons/ServerUtilities#66] opened 2024-05-01 08:00 UTC
EXM   I've been issuing questions for two days, but without a wiki for the configuration file, I'm very confused. Currently, players on my server don't have permission to use the trash can (/trash_can) or join other teams (/team join xxx). How should I add permissions?

**Comment by Lyfts** [comment] 2024-05-01 08:14
You can use `/dump_permissions` to dump a list of all registered permission nodes.

However the two commands you mention are allowed for everyone unless you specifically override it, are you using a bukkit hybrid like Thermos/Crucible/Ultrafine?

**Comment by CrazyNutLz** [comment] 2024-05-01 08:19
> You can use `/dump_permissions` to dump a list of all registered permission nodes.
> 
> However the two commands you mention are allowed for everyone unless you specifically override it, are you using a bukkit hybrid like Thermos/Crucible/Ultrafine?

I am using Crucible as the server backend, but currently, my players cannot use the trash can or join team commands by default. I also didn't see any relevant permissions descriptions in the all_permissions.txt file generated by the /dump_permissions command.

**Comment by Lyfts** [comment] 2024-05-01 08:22
SU can't control command permissions when you're using a bukkit hybrid. You'll have to allow them through whatever bukkit plugin you're using to control permissions.

**Comment by CrazyNutLz** [comment] 2024-05-01 08:26
> SU can't control command permissions when you're using a bukkit hybrid. You'll have to allow them through whatever bukkit plugin you're using to control permissions.

So how should I add the permissions? When players try to use the command, the message they receive is: "I'm sorry, but you don't have permission to perform this command." Does this look like a prompt from SU?
Do I need to use commands from the GroupManager plugin to add permissions? If I am to add permissions using plugin commands, what exactly are the permissions I need to specify?

**Comment by Lyfts** [comment] 2024-05-01 08:28
No that is the vanilla minecraft prompt. I haven't got the slightest clue what the permissions are as it is solely controlled by your bukkit plugin.

**Comment by CrazyNutLz** [comment] 2024-05-01 08:50
> No that is the vanilla minecraft prompt. I haven't got the slightest clue what the permissions are as it is solely controlled by your bukkit plugin.

Perhaps I should indeed add these command permissions for players through the GroupManager plugin. However, I don't know what the permissions are. For example: serverutilities.trash_can? serverutilities.team? These are just my guesses... It's quite confusing...

**Comment by Lyfts** [comment] 2024-05-01 09:01
I doubt it will have serverutilities in its name as groupmanager doesn't interact with forge mods. 
It will probably look like any other command permission, but again I haven't got a clue how they are structured as it isn't controlled by us.

Closing this for now as the issue is out of SU's control.

**Closed by Lyfts** 2024-05-01 09:01 UTC
